<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CareFlux.Application/CareFlux.Application.csproj" />
    <ProjectReference Include="../CareFlux.Domain/CareFlux.Domain.csproj" />
  </ItemGroup>
</Project>
